//Declare Variables to store your first name, last name, marital status, country, and age in multiple lines
let firstName = "Swapnil\n";
let lastName = "Bhadani\n"
let maritalStatus = "Single\n"
let country = "India\n"
let age = "19"
console.log(firstName + lastName + maritalStatus + country + age)
/*Output: Swapnil
          Bhadani
          Single
          India
          19 */

//Declare Variables to store your first name, last name, marital status, country, and age in single line
let firstName = "Swapnil ";
let lastName = "Bhadani "
let maritalStatus = "Single "
let country = "India "
let age = "19 "
console.log(firstName + lastName + maritalStatus + country + age)
//Output: Swapnil Bhadani Single India 19
